# Generated by Django 4.2.5 on 2023-09-13 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0002_pdfupload_textupload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imageupload',
            name='files',
            field=models.ImageField(upload_to='images'),
        ),
    ]
