# Generated by Django 4.2.5 on 2023-09-13 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0003_alter_imageupload_files'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imageupload',
            name='files',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
